import React from 'react'

export default function A1() {
  return (
	<div>
	  <head>
		<title>Article 1</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />	
		<link rel="icon" href="/favicon.ico" />
	  </head>
	  <main>
		<h1>Article 1</h1>
		<p>This is the content of Article 1.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	  </main>
	  <footer>
		<p>&copy; 2023 Red Hat Architects. All rights reserved.</p>
	  </footer>
	</div>
  )
}
